### ISSUE TITLE
NetHack MakeFile 수정

### ISSUE THREAD

**Issue by rocky112358** [mango-tree/webNetHack#16]
MakeFile 안의 NetHack 바이너리가 위치한 디렉토리 수정. nethack 폴더 안에 최상위 위치에 두기로 함.

**Comment by rocky112358** [comment]
바이너리 위치는 그대로 하고 HACKDIR를 수정해보려 합니다.

**Comment by rocky112358** [comment]
MakeFile이 여러개라서 각 파일 모두 수정해야할 것 같습니다...

**Comment by mango-tree** [comment]
넷핵 실행시 Unable to open SYSCF_FILE. 에러가 발생합니다

**Comment by mango-tree** [comment]
다시 테스트해보니 잘 작동합니다
