### ISSUE TITLE
게임플레이화면 고정폭 폰트 적용

### ISSUE THREAD

**Issue by rocky112358** [mango-tree/webNetHack#17]
게임플레이 화면 palatte에 고정폭 폰트를 적용했으면 합니다... 폰트 추천받아요

**Comment by mango-tree** [comment]
우리의 친구 monaco 어떰

**Comment by rocky112358** [comment]
https://www.myfonts.com/fonts/apple/monaco/licensing.html
모나코 웹폰트 유료네요...ㅋㅋ 다른건 어때요?

**Comment by queuedq** [comment]
Roboto Mono - Apache License
Droid Sans Mono - Apache License
Bitstream Vera Sans Mono - [License (GNOME custom)](https://www.gnome.org/fonts/)
Ubuntu Mono - [Ubuntu Font License](http://font.ubuntu.com/ufl/)

개인적으로 Ubuntu Mono 정말 예쁘다고 생각하고 Roboto Mono도 좋습니다

**Comment by queuedq** [comment]
https://fonts.google.com/?category=Monospace
여기 있는 건 전부 무료 폰트

**Comment by rocky112358** [comment]
@queued37 @mango-tree Ubuntu Mono 적용시켜봤어요 괜찮은듯? 근데 게임보드 테두리 있으면 더 좋을 것 같아요... 게임부분만 검정바탕에 흰 글씨 하는건 어때요??

캐릭터 무빙은 아직 디버깅 덜해서 이상할 수 있어요

**Comment by mango-tree** [comment]
이거 적용 했으니까 이슈 닫을게요
