### ISSUE TITLE
메인 페이지 제작

### ISSUE THREAD

**Issue by mango-tree** [mango-tree/webNetHack#3]

**Comment by mango-tree** [comment]
@rocky112358 @DryRain15 @queued37 기본적인 틀만 만들었으니 혹시 수정하고 싶은 분들은 이슈파고 커밋 올려주세여

**Comment by mango-tree** [comment]
@rocky112358 의견 말씀하세여

**Comment by rocky112358** [comment]
0. Nethack -> 정식명칭인 NetHack으로 표기 통일하면 좋을 것 같아요.
1. 푸터에 제 닉네임 SleepyBear (첫 글자를 대문자로)로 수정해야해요.
2. 영어 description 문법이랑 표현 조금 수정해야할 것 같아요.
3. 중앙에 파란색 Play버튼 상하여백이 다른데 글씨가 중앙에 오도록 수정하면 좋을 것 같아요.
4. WHY SERVER? 보다 WHY WEBNETHACK? 은 어때요?
5. 상단 내비게이터에 Login 글씨만 좀 진한 것 같은데 로그인 버튼 강조하려면 우측 상단으로 빼는 건 어때요?

**Comment by mango-tree** [comment]
@rocky112358 description 문법?
Nethack? 이 부분은 넷핵 홈페이지 설명 그대로 복붙한거라서..
다른건 적용할게여

**Comment by rocky112358** [comment]
네 WHY WEBNETHACK? 내용이요 좀 더 가볍고 힙하게 쓰면 좋을듯 (?)

**Comment by mango-tree** [comment]
@rocky112358 수정한 거 i3에 있으니 봐주세여

**Comment by rocky112358** [comment]
@mango-tree 
0. 제 닉네임 SsleepyBear라고 오타났어요...
1. Play 글씨 버튼 내 상하여백 안맞아요
2. WHY WEBNETHACK? 문법이랑 표현 빠진 것 좀 수정해보았어요.
If you want "to" put up your game, playing on "a" server can be a good solution. Also, the server "saves" your game "turn by turn", so you don't have to worry about "losing" your save file. This site is the only one "website" that "you can" play NetHack tile version on server-side "auto-save platform".

**Comment by mango-tree** [comment]
@rocky112358 댕큐합니다 최종확인부탁여

**Comment by rocky112358** [comment]
@mango-tree 으아아 따옴표는 기존 텍스트에서 추가한 부분 표시한건데...따옴표는 빼주세요 ㅠㅠ 그리고 상하여백은 아직 미묘하게 다른거같아요... 폰트가 미묘해서 그런가

**Comment by mango-tree** [comment]
@rocky112358 흠 이거 일단 닫을까여

**Comment by rocky112358** [comment]
@mango-tree 네 닫읍시다!
