### ISSUE TITLE
JQuery를 쓸지 말지 논의

### ISSUE THREAD

**Issue by mango-tree** [mango-tree/webNetHack#5]
현재 JQuery를 이용하고 있지만, 굳이 JQuery를 쓸 만큼 앱이 거대하지 않기 때문에 제거하는 것에 대한 논의가 필요함.
의견 달아주세용

**Comment by rocky112358** [comment]
제거해도 괜찮을거같아요. 테스트 환경은 크롬으로 통일...

**Comment by mango-tree** [comment]
ㅇㅇ익스플로러를 버리면 삶이 편해집니다
그럼 지우는걸로
