### ISSUE TITLE
Front CSS Web Framework 논의

### ISSUE THREAD

**Issue by mango-tree** [mango-tree/webNetHack#6]
개인적으로 생각하고 있는건 [PureCSS](https://purecss.io/)
https://purecss.io/layouts/pricing/
https://purecss.io/layouts/marketing/
이 정도 디자인이면 ㄱㅊ을거같은데 다른 생각이 있는지 알려주세여

**Comment by mango-tree** [comment]
@rocky112358 @queued37 이거 우선적으로 정해주면 ㄳ하겠습니다

**Comment by rocky112358** [comment]
좋은거같아요 PureCSS 찬성!

**Comment by mango-tree** [comment]
별 다른 이견 없으면 PureCSS로 하겠습니다.
