### ISSUE TITLE
사용할 DB 종류 논의

### ISSUE THREAD

**Issue by mango-tree** [mango-tree/webNetHack#8]
뭐쓰지?
- MySQL
- PostgreSQL
- SQLite3
- MariaDB

**Comment by rocky112358** [comment]
DB 쿼리를 얼마나 많이보내는지가 중요할거같은데 인풋 하나마다 쿼리줄거면 SQLite3 띄엄띄엄 프로그레스만 저장할거면 원격 DB도 괜찮을듯요 종류는 윙자에 깔려있는것으로 해야지...

**Comment by mango-tree** [comment]
ㄴㄴ쿼리는 별로 보낼 일이 없음. 게임 돌린 후 세이브파일 이름 저장용 정도?
그래서 부담없이 고르면 됨. 원격 DB도 괜찮을듯

**Comment by rocky112358** [comment]
DB 각 컬럼에 각 스탯을 넣는게 아니라 세이브파일 이름정도만 저장하는거라면... 어떤걸 써도 상관 없을듯하네요.

**Comment by mango-tree** [comment]
ㅇㅇ이제 세이브파일을 어디에 저장할지가 중요할듯...
그럼 뭐쓰지? 개발하기 편하게 SQLite3?

**Comment by rocky112358** [comment]
찬성합니다!

**Comment by mango-tree** [comment]
ㅇㅇㅋ SQLlite3로 하겠습니다 땅땅땅
